=== zuzqqa/formula1_website_project/hih.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
<xs:element name="hipertext" type="hipertextType"/> 
	<xs:complexType name="hipertextType"> 
		<xs:sequence>
			<xs:element name="student" type="studentType" /> 	
			<xs:element name="definition" type="definitionType"/>
			<xs:element name="date" type="xs:date"/>
			<xs:element name="drivers" type="driversType"/>
			<xs:element name="teams" type="teamsType"/>	
		</xs:sequence>
	</xs:complexType>

    <xs:attribute name="worldchampion">
        <xs:simpleType> 
			<xs:restriction base="xs:string">
 				<xs:enumeration value="yes"/>
				<xs:enumeration value="no"/>
			</xs:restriction>
		</xs:simpleType>
    </xs:attribute>

	<xs:simpleType name="definitionType"> 
		<xs:restriction base="xs:string">
			<xs:minLength value="15"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="shortStringType"> 
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="30"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="longStringType"> 
		<xs:restriction base="xs:string">
			<xs:minLength value="11"/>
			<xs:maxLength value="200"/>
		</xs:restriction>
	</xs:simpleType>

    <xs:simpleType name="driverID"> 
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9]{4}-[0-9]{4}-[0-9]{4})|([0-9]{3}-[0-9]{3}-[0-9]{3}-[0-9]{3})"/>
        </xs:restriction>
    </xs:simpleType>

	<xs:element name="image" type="adressType"/>
	<xs:element name="link" type="adressType"/>
	
    <xs:group name="info"> 
        <xs:sequence>
            <xs:element name="nameMix" type="nameMixType"/>
            <xs:element name="about">
                <xs:complexType> 
                    <xs:sequence>
                        <xs:element name="description" type="longStringType"/>
                        <xs:element name="championships" type="championships"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    
    <xs:complexType name="nameMixType" mixed="true"> 
        <xs:sequence>
            <xs:element name="name" maxOccurs="2" type="xs:string"/>
            <xs:element name="position">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="3"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:any minOccurs="0"/> 
        </xs:sequence>
    </xs:complexType>

	<xs:complexType name="studentType"> 
		<xs:sequence>
			<xs:element name="name" type="shortStringType" />	
			<xs:element name="surname" type="shortStringType" />
        </xs:sequence>
	</xs:complexType>

    <xs:complexType name="driversType">
        <xs:sequence>
            <xs:element name="driver" type="driverType" minOccurs="1" maxOccurs="3"/>
        </xs:sequence>
    </xs:complexType>

	<xs:complexType name="achivementType"> 
		<xs:sequence>
			<xs:element name="title" type="shortStringType"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
    	<xs:attribute name="championship">
			<xs:simpleType>
				<xs:restriction base="xs:string">
 					<xs:enumeration value="yes"/>
					<xs:enumeration value="no"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="driverType"> 
		<xs:complexContent>
			<xs:extension base="studentType"> 
					<xs:sequence>
                        <xs:element name="number" type="unionType"/>
                        <xs:element name="id" type="driverID"/>
                        <xs:element name="position" type="xs:integer"/>
                        <xs:element name="aboutDriver">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="age"/>
									<xs:element name="country"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element name="achievements">
						    <xs:complexType> 
						        <xs:sequence>
							        <xs:element name="achievement" type="achivementType" minOccurs="0" maxOccurs="unbounded"/>
						        </xs:sequence>
                                <xs:attribute name="wonArace" use="required">
                                    <xs:simpleType> 
					                    <xs:restriction base="xs:string">
 						                    <xs:enumeration value="yes"/>
						                    <xs:enumeration value="no"/>
					                    </xs:restriction>
					                </xs:simpleType>
                                </xs:attribute>
						    </xs:complexType>
						</xs:element>
					</xs:sequence>
				<xs:attribute name="top3" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
 							<xs:enumeration value="yes"/>
							<xs:enumeration value="no"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
                <xs:attribute name="top5" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
 							<xs:enumeration value="yes"/>
							<xs:enumeration value="no"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
                <xs:attribute ref="worldchampion"/> 
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="teamsType"> 
		<xs:sequence>
			<xs:element name="team" minOccurs="3" maxOccurs="3">
				<xs:complexType>
					<xs:sequence>
						<xs:group ref="info" minOccurs="1"/> 
						<xs:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
                    <xs:attribute ref="worldchampion"/> 
					<xs:attribute name="championship">
						<xs:simpleType> 
							<xs:restriction base="xs:string">
								<xs:enumeration value="yes"/>
								<xs:enumeration value="no"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="adressType"> 
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="source" type="xs:anyURI" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

    <xs:simpleType name="championshipTitle"> 
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="2000"/>
            <xs:maxInclusive value="2022"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="championshipTitles"> 
        <xs:list itemType="championshipTitle"/> 
    </xs:simpleType>

    <xs:simpleType name="championships"> 
        <xs:restriction base="championshipTitles">
            <xs:length value="5"/> 
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="unionType"> 
        <xs:union>
            <xs:simpleType> 
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1"/>
                    <xs:maxInclusive value="3"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType> 
                <xs:restriction base="xs:string">
                    <xs:enumeration value="One"/>
                    <xs:enumeration value="Two"/>
                    <xs:enumeration value="Three"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
</xs:schema>

=== zuzqqa/formula1_website_project/xmldoxsd.xml
<?xml version="1.0" encoding="utf-8" standalone = "no"?>
<hipertext xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="hih.xsd">
	<student>
		<name>Zuzanna</name>
		<surname>Nowak</surname>
    </student>

	<definition>
		Formula 1 is the most famous motorsport.
	</definition>
	
	<date>
		2022-11-29
	</date>

	<drivers>
		<driver top3="yes" top5="yes" worldchampion="yes">
			<name>Max</name>
			<surname>Verstappen</surname>
			<number>1</number>
			<id>134-143-234-999</id>
            <position>1</position>
			<aboutDriver>
				<age>25</age>
				<country>The Netherlands</country>
			</aboutDriver>
			<image source="max_ver.png">Max Verstappen</image>
			<link source="https://www.formula1.com/en/results.html/2022/races/1125/saudi-arabia/race-result.html">Saudi Arabia</link>
			<achievements wonArace="yes">
				<achievement championship="yes">
					<title>2021 WDC</title>
					<description>
						Max won championship after thrilling and controversial race in Abu Dhabi.
					</description>
					<image source="image10.png">Max fought Hamilton</image>
				</achievement>
                <achievement championship="yes">
					<title>2022 WDC</title>
					<description>
						Max won championship in Japan after dominating the whole season.
					</description>
					<image source="max_championship.jpg">Project of Memex</image>
				</achievement>
			</achievements>
		</driver>
		<driver top3="yes" top5="yes" worldchampion="yes">
			<name>Charles</name>
			<surname>Leclerc</surname>
			<number>Two</number>
			<id>1934-1432-2345</id>
            <position>2</position>
			<aboutDriver>
				<age>25</age>
				<country>Monaco</country>
			</aboutDriver>
			<image source="charles_lec.png">Charles Leclerc</image>
			<link source="https://www.formula1.com/en/drivers/charles-leclerc.html">Charles Leclerc</link>
			<achievements wonArace="yes">
				<achievement championship="no">
					<title>Vice World Champion</title>
					<description>
						He fought with Checo Perez until the very end of the season but managed to secure his second position in WDC classification.
					</description>
					<image source="france_leclerc.jpg">Crucial moment of the season- Charles crashes in France, after which many happen to consider this event as the breaking point of his and Max's battle for WDC</image>
				</achievement>
			</achievements>
		</driver>
        <driver top3="yes" top5="yes" worldchampion="no">
			<name>Checo</name>
			<surname>Perez</surname>
			<number>Three</number>
			<id>1934-1432-2345</id>
            <position>3</position>
			<aboutDriver>
				<age>32</age>
				<country>Mexico</country>
			</aboutDriver>
			<image source="sergio_per.png">Checo Perez</image>
			<link source="https://www.formula1.com/en/drivers/sergio-perez.html">Checo Perez</link>
			<achievements wonArace="yes">
				<achievement championship="no">
					<title>3rd place in WDC</title>
					<description>
						Perez took the third position as F1 2022 season came to the end.
					</description>
					<image source="monaco_gp.png">Checo won memorable 2022 Monaco GP</image>
				</achievement>
			</achievements>
		</driver>
	</drivers>
    <teams>
        <team worldchampion="yes">
			<nameMix>
			<name>Reb Bull</name>
			<name>Red Bull Racing</name>
            <position>1</position>
			</nameMix>
            <about>
				<description>Red Bull is mainly assosciated with energy drinks but it is also one of the best formula 1 teams ever.</description>
				<championships>2022 2019 2012 2000 2012</championships>
			</about>
            <image source="redbull.png">Red Bull logo</image>
        </team>
        <team worldchampion="yes">
			<nameMix>
            <name>Ferrari</name>
            <position>2</position>
			</nameMix>
            <about>
				<description>Ferarri is probably the most popular formula 1 team. It's impact on motorsport is unquestioned. ,,Everyone is a Ferrari fan. Even if they say they're not, they are Ferrari fans.</description>
				<championships>2022 2019 2012 2000 2012</championships>	
			</about>
			<image source="ferrari.png">Ferrari logo</image>
        </team>
        <team worldchampion="no">
			<nameMix>
            <name>Mercedes</name>
            <position>3</position>
			</nameMix>
            <about>
				<description>Mercedes is a germany team.</description>
				<championships>2022 2019 2012 2000 2012</championships>
			</about>
            <image source="merc.png">Mercedes logo</image>
        </team>
    </teams>
</hipertext>
